# Generated by Django 4.0 on 2021-12-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('uploading_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=50)),
                ('isRejected', models.BooleanField()),
                ('Creatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatorname', to='auth.user')),
                ('Qualityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualityname', to='auth.user')),
                ('Sheetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='uploading_data.sheet')),
            ],
        ),
    ]
