# Generated by Django 4.0 on 2021-12-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading_data', '0002_data_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='batchNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheeturl',
            field=models.FileField(upload_to=''),
        ),
    ]
