# Generated by Django 4.0 on 2021-12-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading_data', '0003_sheet_batchnumber_alter_sheet_sheeturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='batchNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='ticketname',
            field=models.IntegerField(),
        ),
    ]
