# Generated by Django 4.0 on 2021-12-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading_data', '0005_alter_sheet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheeturl',
            field=models.FileField(upload_to='Files/'),
        ),
    ]
