# Generated by Django 4.0 on 2022-01-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading_data', '0006_alter_sheet_sheeturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_field',
            name='SKU',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
