# Generated by Django 4.0 on 2022-01-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading_data', '0007_alter_data_field_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheeturl',
            field=models.FileField(unique=True, upload_to='Files/'),
        ),
    ]
